# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pc_pop_get_skeleton_cpp <- function(var_list) {
    .Call(`_LocalPC_pc_pop_get_skeleton_cpp`, var_list)
}

pc_pop_cpp <- function(true_dag, names, lmax = 3L, verbose = TRUE, verbose_small = TRUE) {
    .Call(`_LocalPC_pc_pop_cpp`, true_dag, names, lmax, verbose, verbose_small)
}

rcpp_hello_world <- function() {
    .Call(`_LocalPC_rcpp_hello_world`)
}

