# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pc_sample_cpp <- function(true_dag, df, target, names, lmax = 3L, signif_level = 0.05, verbose = TRUE, verbose_small = TRUE) {
    .Call(`_LocalPC_pc_sample_cpp`, true_dag, df, target, names, lmax, signif_level, verbose, verbose_small)
}

pc_sample_get_skeleton_efficient_cpp <- function(var_list, df, signif_level = 0.05) {
    .Call(`_LocalPC_pc_sample_get_skeleton_efficient_cpp`, var_list, df, signif_level)
}

pc_sample_efficient_cpp <- function(true_dag, df, target, names, lmax = 3L, signif_level = 0.05, verbose = TRUE, verbose_small = TRUE) {
    .Call(`_LocalPC_pc_sample_efficient_cpp`, true_dag, df, target, names, lmax, signif_level, verbose, verbose_small)
}

get_partial_correlation <- function(C, i, j, k) {
    .Call(`_LocalPC_get_partial_correlation`, C, i, j, k)
}

fisherZ <- function(pc, n, k_size) {
    .Call(`_LocalPC_fisherZ`, pc, n, k_size)
}

condIndTest <- function(C, i, j, k, n, signif_level) {
    .Call(`_LocalPC_condIndTest`, C, i, j, k, n, signif_level)
}

pc_pop_skeleton_setup_cpp <- function(true_dag, names, lmax, verbose) {
    .Call(`_LocalPC_pc_pop_skeleton_setup_cpp`, true_dag, names, lmax, verbose)
}

pc_pop_get_skeleton_cpp <- function(var_list) {
    .Call(`_LocalPC_pc_pop_get_skeleton_cpp`, var_list)
}

pc_pop_cpp <- function(true_dag, names, lmax = 3L, verbose = TRUE, verbose_small = TRUE) {
    .Call(`_LocalPC_pc_pop_cpp`, true_dag, names, lmax, verbose, verbose_small)
}

get_current_edges <- function(i, p, graph) {
    .Call(`_LocalPC_get_current_edges`, i, p, graph)
}

combn_cpp <- function(x, l) {
    .Call(`_LocalPC_combn_cpp`, x, l)
}

get_neighbors_from_dag <- function(i, p, true_dag) {
    .Call(`_LocalPC_get_neighbors_from_dag`, i, p, true_dag)
}

create_conditioning_sets_efficient_cpp2 <- function(neighbors) {
    .Call(`_LocalPC_create_conditioning_sets_efficient_cpp2`, neighbors)
}

pc_sample_skeleton_setup_efficient_cpp <- function(true_dag, target, names, lmax, verbose) {
    .Call(`_LocalPC_pc_sample_skeleton_setup_efficient_cpp`, true_dag, target, names, lmax, verbose)
}

change_S_efficient <- function(S, i, j, sep) {
    invisible(.Call(`_LocalPC_change_S_efficient`, S, i, j, sep))
}

change_S_0_efficient <- function(S, i, j) {
    invisible(.Call(`_LocalPC_change_S_0_efficient`, S, i, j))
}

get_potential_sep <- function(i, j, neighborhood, p, true_dag) {
    .Call(`_LocalPC_get_potential_sep`, i, j, neighborhood, p, true_dag)
}

check_separation_sample_efficient <- function(l, i, j, kvals, sep, true_dag, names, neighborhood, C, S, pval, num_tests, R, n, signif_level, verbose) {
    invisible(.Call(`_LocalPC_check_separation_sample_efficient`, l, i, j, kvals, sep, true_dag, names, neighborhood, C, S, pval, num_tests, R, n, signif_level, verbose))
}

makeFinalGraph <- function(G, C, neighborhood, N) {
    invisible(.Call(`_LocalPC_makeFinalGraph`, G, C, neighborhood, N))
}

