# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_partial_correlation <- function(C, i, j, k) {
    .Call(`_LocalPC_get_partial_correlation`, C, i, j, k)
}

fisherZ <- function(pc, n, k_size) {
    .Call(`_LocalPC_fisherZ`, pc, n, k_size)
}

condIndTest <- function(C, i, j, k, n, signif_level) {
    .Call(`_LocalPC_condIndTest`, C, i, j, k, n, signif_level)
}

pc_pop_get_skeleton_cpp <- function(var_list) {
    .Call(`_LocalPC_pc_pop_get_skeleton_cpp`, var_list)
}

pc_sample_get_skeleton_cpp <- function(var_list, df, signif_level = 0.95) {
    .Call(`_LocalPC_pc_sample_get_skeleton_cpp`, var_list, df, signif_level)
}

pc_pop_cpp <- function(true_dag, names, lmax = 3L, verbose = TRUE, verbose_small = TRUE) {
    .Call(`_LocalPC_pc_pop_cpp`, true_dag, names, lmax, verbose, verbose_small)
}

pc_sample_cpp <- function(true_dag, df, target, names, lmax = 3L, signif_level = 0.95, verbose = TRUE, verbose_small = TRUE) {
    .Call(`_LocalPC_pc_sample_cpp`, true_dag, df, target, names, lmax, signif_level, verbose, verbose_small)
}

rcpparma_hello_world <- function() {
    .Call(`_LocalPC_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_LocalPC_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_LocalPC_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_LocalPC_rcpparma_bothproducts`, x)
}

